apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-backend
  template:
    metadata:
      labels:
        app: generator-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: 8000 