apiVersion: v1
kind: Service
metadata:
  name: generator-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
  selector:
    app: generator-frontend 