version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: generator-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: generator_db
      MYSQL_USER: generator_user
      MYSQL_PASSWORD: generator_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: generator-backend
    ports:
      - "8000:8000"
    # environment:
      # - DATABASE_URL=mysql+pymysql://generator_user:generator_password@mysql:3306/generator_db
    volumes:
      - ./generated_files:/app/generated_files
    restart: unless-stopped
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: generator-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend 

volumes:
  mysql_data: 