services:
  backend:
    build: ./backend
    container_name: generator-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    volumes:
      - ./generated_files:/app/generated_files
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: generator-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - backend 